### 텐서(Tensor) 살펴보기
- Pytorch에서 데이터 저장 자료형
- 모델 입력(input), 출력(output) 데이터 형태

- 모듈 로딩

In [2]:
import torch

- Tensor 속성 관련 함수

In [3]:
# 매개 변수 : 텐서 인스턴스, 텐서 변수명
def print_attr(tensor, name) :
    print(f'[Tensor {name}]\'s Attribute')
    print(f'- tensor.shape : {tensor.shape}')
    print(f'- tensor.ndim : {tensor.ndim}D')
    print(f'- tensor.dtype : {tensor.dtype}')
    print(f'- tensor.device : {tensor.device}')
    print(f'- tensor.requires_grad : {tensor.requires_grad}')
    print(f'- tensor.data : {tensor.data}')
    print()

- Tensor 생성 (1) 특정 데이터 타입의 Tensor 생성
    * 타입별 텐서 클래스 생성자 활용
    * 예) IntTensor(), FloatTensor(), BoolTensor()

In [4]:
# 정수 타비 텐서 생성
t1 = torch.IntTensor(10) # 괄호안에는 shape...?
t2 = torch.IntTensor([10, 22]) # 실수인 10.0를 넣어도 정수로 변환해줌. but 소수점 뒷자리를 날리기 때문에 손실 관련 워닝 발생.
t3 = torch.BoolTensor([1,1,0,-1])
t4 = torch.FloatTensor([10, 20]) # 정수로 넣어도 실수로 변환.

In [5]:
print_attr(t1, 't1')

print_attr(t2,'t2')

print_attr(t3,'t3')

print_attr(t4,'t4')

[Tensor t1]'s Attribute
- tensor.shape : torch.Size([10])
- tensor.ndim : 1D
- tensor.dtype : torch.int32
- tensor.device : cpu
- tensor.requires_grad : False
- tensor.data : tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=torch.int32)

[Tensor t2]'s Attribute
- tensor.shape : torch.Size([2])
- tensor.ndim : 1D
- tensor.dtype : torch.int32
- tensor.device : cpu
- tensor.requires_grad : False
- tensor.data : tensor([10, 22], dtype=torch.int32)

[Tensor t3]'s Attribute
- tensor.shape : torch.Size([4])
- tensor.ndim : 1D
- tensor.dtype : torch.bool
- tensor.device : cpu
- tensor.requires_grad : False
- tensor.data : tensor([ True,  True, False,  True])

[Tensor t4]'s Attribute
- tensor.shape : torch.Size([2])
- tensor.ndim : 1D
- tensor.dtype : torch.float32
- tensor.device : cpu
- tensor.requires_grad : False
- tensor.data : tensor([10., 20.])



- Tensor 생성 (2) 원하는 값으로 텐서 생성 => torch.tensor()

In [6]:
t1 = torch.tensor(10) # scalar 데이터, int64
print_attr(t1, 't1')

[Tensor t1]'s Attribute
- tensor.shape : torch.Size([])
- tensor.ndim : 0D
- tensor.dtype : torch.int64
- tensor.device : cpu
- tensor.requires_grad : False
- tensor.data : 10



In [7]:
t1 = torch.tensor(10.) #scalar 데이터, float32 
print_attr(t1, 't1')

[Tensor t1]'s Attribute
- tensor.shape : torch.Size([])
- tensor.ndim : 0D
- tensor.dtype : torch.float32
- tensor.device : cpu
- tensor.requires_grad : False
- tensor.data : 10.0



In [8]:
# dtype 매개변수 : 원하는 데이터 타입 지정 가능.
t1 = torch.tensor(10., dtype=torch.int32) #scalar 데이터, int6int32 ==> 워닝 발생
print_attr(t1, 't1')

[Tensor t1]'s Attribute
- tensor.shape : torch.Size([])
- tensor.ndim : 0D
- tensor.dtype : torch.int32
- tensor.device : cpu
- tensor.requires_grad : False
- tensor.data : 10



C:\Users\KDP-48\AppData\Local\Temp\ipykernel_40788\812114866.py:2: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  t1 = torch.tensor(10., dtype=torch.int32) #scalar 데이터, int6int32 ==> 워닝 발생


In [9]:
t1 = torch.tensor(10., dtype=torch.bool) #scalar 데이터 --> float32 ▶ bool
print_attr(t1, 't1')

[Tensor t1]'s Attribute
- tensor.shape : torch.Size([])
- tensor.ndim : 0D
- tensor.dtype : torch.bool
- tensor.device : cpu
- tensor.requires_grad : False
- tensor.data : True



In [10]:
t1 = torch.tensor([1,2,3], dtype=torch.int8) # 1D 데이터
print_attr(t1, 't1')

[Tensor t1]'s Attribute
- tensor.shape : torch.Size([3])
- tensor.ndim : 1D
- tensor.dtype : torch.int8
- tensor.device : cpu
- tensor.requires_grad : False
- tensor.data : tensor([1, 2, 3], dtype=torch.int8)



In [11]:
t1 = torch.tensor([[1,2,3]], dtype=torch.int8)# 2D 데이터
print_attr(t1, 't1')

[Tensor t1]'s Attribute
- tensor.shape : torch.Size([1, 3])
- tensor.ndim : 2D
- tensor.dtype : torch.int8
- tensor.device : cpu
- tensor.requires_grad : False
- tensor.data : tensor([[1, 2, 3]], dtype=torch.int8)



- Tensor 생성(3) - 특정 값으로 채운 텐서 => 0, 1 등의 값

In [12]:
# 0으로 채운 텐서
t1 = torch.zeros(5)
print_attr(t1, 't1')

[Tensor t1]'s Attribute
- tensor.shape : torch.Size([5])
- tensor.ndim : 1D
- tensor.dtype : torch.float32
- tensor.device : cpu
- tensor.requires_grad : False
- tensor.data : tensor([0., 0., 0., 0., 0.])



In [13]:
# 0으로 채운 텐서
t1 = torch.zeros((5,5), dtype = torch.int8)
print_attr(t1, 't1')

[Tensor t1]'s Attribute
- tensor.shape : torch.Size([5, 5])
- tensor.ndim : 2D
- tensor.dtype : torch.int8
- tensor.device : cpu
- tensor.requires_grad : False
- tensor.data : tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]], dtype=torch.int8)



In [14]:
# 1으로 채운 텐서
t1 = torch.ones((2,4), dtype = torch.int8)
print_attr(t1, 't1')

[Tensor t1]'s Attribute
- tensor.shape : torch.Size([2, 4])
- tensor.ndim : 2D
- tensor.dtype : torch.int8
- tensor.device : cpu
- tensor.requires_grad : False
- tensor.data : tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int8)



In [15]:
# 이미 존재하는 텐서와 동일한 shape으로 잡고 값 채우기 => zeros_like(), ones_like()
img=torch.tensor([[2, 3, 4, 5, 6, 7], [2, 3, 4, 5, 6, 7]])
print(img.shape)

torch.Size([2, 6])


In [16]:
# 이미 존재하는 텐서와 동일한 shape에 0 채우기.
zero_img = torch.zeros_like(img)
print(zero_img)

tensor([[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]])


In [17]:
ones_img = torch.ones_like(img)
print(ones_img)

tensor([[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]])


In [18]:
full_img = torch.full_like(img, 7)
print(full_img)

tensor([[7, 7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7, 7]])


In [19]:
# 대각선 방향으로 1 채우기 = eye()
t1 = torch.eye(5) # 5x5 행렬 생성 후 대각선으로 1 채우기
print(t1)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [20]:
# 대각선 방향으로 1 채우기 = eye()
t1 = torch.eye(2, 3) # 2x3 행렬 생성 후 대각선으로 1 채우기
print(t1)

tensor([[1., 0., 0.],
        [0., 1., 0.]])


- Tensor 생성 방법 (4) : 임의의 값으로 Tensor 생성 => torch.rand(), torch.randn(), torch.randint()

In [21]:
torch.manual_seed(12) # 랜덤 초기값 설정.
t5 = torch.rand(2,3) # [0, 1) 분포 안에서 랜덤 생성
t6 = torch.randn(2, 3) # standard normal 분포에서 랜덤 생성
t7 = torch.randint(low=1, high =10, size = (2, 3)) # low, high) low<= 값 < high

In [22]:
print(t5, t6, t7, sep='\n\n')

tensor([[0.4657, 0.2328, 0.4527],
        [0.5871, 0.4086, 0.1272]])

tensor([[ 1.5869,  1.1268, -1.2274],
        [-0.8216, -1.7861,  0.6167]])

tensor([[8, 4, 6],
        [2, 2, 2]])


- Tensor 생성 방법 (5) : Ndarray 객체 활용 => torch.from_numpy(), torch.as_tensor(), tensor()

In [23]:
# 데이터생성
import numpy as np

data = np.array([11, 22, 33])
print(data, type(data))

[11 22 33] <class 'numpy.ndarray'>


In [24]:
t1 = torch.from_numpy(data)
print(t1)

tensor([11, 22, 33], dtype=torch.int32)


In [25]:
t2 = torch.as_tensor(data)
print(t2)

tensor([11, 22, 33], dtype=torch.int32)


In [26]:
t3 = torch.tensor(data)
print(t3)

tensor([11, 22, 33], dtype=torch.int32)


In [27]:
# ndarray 원소 변경
data[0] =100

In [28]:
# from_numpy(), as_tensor() => 데이터 공유
# tensor() => 복사본 생성
print(data, t1, t2, t3, sep='\n') # t1, t2는 변경. t3는 변경X 

[100  22  33]
tensor([100,  22,  33], dtype=torch.int32)
tensor([100,  22,  33], dtype=torch.int32)
tensor([11, 22, 33], dtype=torch.int32)
