### Tensor 원소/요소 접근 
- 인덱싱과 슬라이싱

In [1]:
# 모듈 로딩 
import torch

In [2]:
# 텐서 생성
points=torch.tensor([[4., 2], [5.,3.], [6., 4.]], dtype=torch.int16)
points

C:\Users\KDP-48\AppData\Local\Temp\ipykernel_40448\1521202682.py:2: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  points=torch.tensor([[4., 2], [5.,3.], [6., 4.]], dtype=torch.int16)


tensor([[4, 2],
        [5, 3],
        [6, 4]], dtype=torch.int16)

In [3]:
# 텐서의 원소 1개 접근
# 데이터 3 추출
print(points[1,1])

tensor(3, dtype=torch.int16)


In [4]:
# 데이터 1번 행부터 나머지 모든 행 추출
print(points[1:])

# 데이터 4 추출
print(points[-1, -1])
print(points[2, 1])

tensor([[5, 3],
        [6, 4]], dtype=torch.int16)
tensor(4, dtype=torch.int16)
tensor(4, dtype=torch.int16)


-브로드 캐스팅 연산

In [5]:
# case2 : 벡터와 행렬
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([3])
print(f'm1.shape => {m1.shape}')
print(f'm2.shape => {m2.shape}')

m1.shape => torch.Size([1, 2])
m2.shape => torch.Size([1])


In [6]:
m3 = m1+m2
print(f'm3 => {m3.shape}')

m3 => torch.Size([1, 2])


In [7]:
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([[3], [4]])
print(f'm1.shape => {m1.shape}')
print(f'm2.shape => {m2.shape}')

m1.shape => torch.Size([1, 2])
m2.shape => torch.Size([2, 1])


In [8]:
m3 = m1*m2
m4 = m1.mul(m2)
print(f'm3.shape => {m3.shape}\n')
print(f'm3 =>\n{m3}')

print(f'm4.shape => {m4.shape}\n')
print(f'm4 =>\n{m4}')

m3.shape => torch.Size([2, 2])

m3 =>
tensor([[3., 6.],
        [4., 8.]])
m4.shape => torch.Size([2, 2])

m4 =>
tensor([[3., 6.],
        [4., 8.]])


In [9]:
# 원소 단위 연산 수행 메서드들 
m1.add(m2), m1.sub(m2), m1.mul(m2), m1.div(m2)

(tensor([[4., 5.],
         [5., 6.]]),
 tensor([[-2., -1.],
         [-3., -2.]]),
 tensor([[3., 6.],
         [4., 8.]]),
 tensor([[0.3333, 0.6667],
         [0.2500, 0.5000]]))