### Tensor shape 변경
- reshape(), view() : 원소 개수가 유지됨. 기존 텐서를 공유함(원본 변경 시 함께 변경됨)


In [3]:
# 모듈 로딩
import torch

In [4]:
# 텐서 데이터 생성 
t1 = torch.tensor([[1,2,3], [4,5,6]])
print(t1.shape, t1.ndim)
print(t1)

torch.Size([2, 3]) 2
tensor([[1, 2, 3],
        [4, 5, 6]])


In [5]:
# 2행 3열 => 3행 2열로 변경 : 원소 수 동일(6개).
t1.view(3, 2) # view 반환값 --> tensor 

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [6]:
# 2행 3열 => 6행 1열로 변경 : 원소 수 동일(6개).
t1.view(6,1) # view 반환값 --> tensor 

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [7]:
# 2행 3열 => 6행 1열로 변경 : 원소 수 동일(6개).
# -1 : 원소 수를 알아서 행에 할당.

t1 = torch.tensor([[1,2,3], [4,5,6]])
print('t1', t1, '\n', 't1.view(-1, 1)', t1.view(-1, 1), sep='\n')

print(t1.view(6, -1))

t1
tensor([[1, 2, 3],
        [4, 5, 6]])


t1.view(-1, 1)
tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])
tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])


In [8]:
# tensor.reshape()
t1.reshape(2,3)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [9]:
# 원소 수가 유지되어야 함.
#t1.reshape(-1, 7) # RuntimeError : shape '[-1, 7]' is invalid for input of size 6
#t1.reshape(7, -1) # RuntimeError : # shape '[-1, 7]' is invalid for input of size 6

- 전치 : 열<=> 행 변경 

In [10]:
print(t1.shape)
t2 = t1.T
print(t2.shape, t2.is_contiguous())

torch.Size([2, 3])
torch.Size([3, 2]) False


In [11]:
# t2.view(-1, 6) # RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

t3=t2.reshape(-1, 6)
print(t3.shape, t3.is_contiguous())

torch.Size([1, 6]) True


메모리 
order (scikit learn ---> 'order' = 'c'/'f')

### 텐서 데이터의 메모리 저장 정보 및 메타 데이터
- 현재 저장 형태 검색 방향 정보, 시작 정보

In [29]:
t1 = torch.tensor([[1,2,3], [4,5,6]])
print(t1.shape, t1.ndim)
print(f't1.storage()=>{t1.storage()}')
print(f't1.storage_offset()', {t1.storage_offset()})
print(f't1.stride()=>, {t1.stride}')
print(f't1.is_contiguous()=>, {t1.is_contiguous()}') #연속적인지 확인

torch.Size([2, 3]) 2
t1.storage()=> 1
 2
 3
 4
 5
 6
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 6]
t1.storage_offset() {0}
t1.stride()=>, <built-in method stride of Tensor object at 0x000001F9D872C590>
t1.is_contiguous()=>, True


In [28]:
t2 = t1.view(-1, 2)
print(t2.shape, t2.ndim)
print(f't2.storage()=>{t2.storage()}')
print(f't2.storage_offset(), {t2.storage_offset()}')
print(f't2.stride()=>, {t2.stride()}')
print(f't2.is_contiguous()=>, {t2.is_contiguous()}')

torch.Size([3, 2]) 2
t2.storage()=> 1
 2
 11
 22
 44
 55
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 6]
t2.storage_offset(), 0
t2.stride()=>, (2, 1)
t2.is_contiguous()=>, True


In [14]:
import numpy as np

### 차원 제거/추가
- tensor.squeeze() : 텐서에서 차원이 1인 것 제거
- tensor.unsqueeze(dim) : 텐서에서 차원이 1인 것 추가


In [15]:
# 데이터 생성
t1 = torch.tensor([[1,2], [3,4]])
t2 = torch.tensor([[1,2,3,4]]) 
t2 = torch.tensor([[[1,2,3,4]]]) # 차원 방정식 

In [16]:
print(f't1=> {t1.shape}, {t1.ndim}D, {t1.data_ptr}')
print(f't2=> {t2.shape}, {t2.ndim}D, {t2.data_ptr}')
print(f't3=> {t3.shape}, {t3.ndim}D, {t2.data_ptr}')

t1=> torch.Size([2, 2]), 2D, <built-in method data_ptr of Tensor object at 0x000001F9D8E651D0>
t2=> torch.Size([1, 1, 4]), 3D, <built-in method data_ptr of Tensor object at 0x000001F9D6A63950>
t3=> torch.Size([1, 6]), 2D, <built-in method data_ptr of Tensor object at 0x000001F9D6A63950>


In [17]:
t11 = t1.squeeze()
t22 = t2.squeeze()
t33 = t3.squeeze()
t44 = t3.squeeze(dim=0) # 지정된 것만 (0 데이터수, 1 채널, 2 높이, 3 너비) 순
print(f't1 차원 축소 => {t11.shape}, {t11.ndim}D, {t11.data_ptr}') # 줄일 것이 없음!!
print(f't2 차원 축소 => {t22.shape}, {t22.ndim}D, {t22.data_ptr}') #
print(f't3 차원 축소 => {t33.shape}, {t33.ndim}D, {t33.data_ptr}') #
print(f't4 차원 축소 => {t44.shape}, {t44.ndim}D, {t44.data_ptr}') #

t1 차원 축소 => torch.Size([2, 2]), 2D, <built-in method data_ptr of Tensor object at 0x000001F9D0B944A0>
t2 차원 축소 => torch.Size([4]), 1D, <built-in method data_ptr of Tensor object at 0x000001F9D0B8A950>
t3 차원 축소 => torch.Size([6]), 1D, <built-in method data_ptr of Tensor object at 0x000001F9D8E65630>
t4 차원 축소 => torch.Size([6]), 1D, <built-in method data_ptr of Tensor object at 0x000001F9D0C630E0>


In [18]:
# 원소/ 요소 수 변경 없이 1 차원 증가 시키기 => torch.unsqueeze(dim)
print(f't1 정보 => {t1.shape}, {t1.ndim}D, {t1.data_ptr}, {t1.stride()}')


t1 정보 => torch.Size([2, 2]), 2D, <built-in method data_ptr of Tensor object at 0x000001F9D8E651D0>, (2, 1)


In [19]:
t11 = t1.unsqueeze(dim=0)
t22 = t1.unsqueeze(dim=-1)

print(f't1 차원 추가 => {t11.shape}, {t11.ndim}D, {t11.data_ptr}, {t11.stride()}') # stride 가 몬데...
print(f't2 차원 추가 => {t22.shape}, {t22.ndim}D, {t22.data_ptr}, {t22.stride()}')


t1 차원 추가 => torch.Size([1, 2, 2]), 3D, <built-in method data_ptr of Tensor object at 0x000001F9D8E773B0>, (4, 2, 1)
t2 차원 추가 => torch.Size([2, 2, 1]), 3D, <built-in method data_ptr of Tensor object at 0x000001F9D0B944A0>, (2, 1, 1)


type(torch.XXX) => 형변환 메서드.

<hr>

T -> 행 ↔ 열 (2차원)

### Tensor 차원/ 형태 변경

In [20]:
t1 = torch.tensor([[[1,2], [11,22], [44,55]]])
print(f't1.shape => {t1.shape}, {t1.ndim}D')

t1.shape => torch.Size([1, 3, 2]), 3D


In [21]:
 # 2개의 차원을 변경하는 메서드 
#t1.transpose() #이대로는 오류 빰!
t11 = t1.transpose(0, 2) # HEY T, 0번 자리와 2번 자리를 서로 바꿔줘~
print(f't11.shape => {t11.shape}, {t11.ndim}D')

t11.shape => torch.Size([2, 3, 1]), 3D


In [22]:
 # 2개의 차원을 변경하는 메서드 
t22 = t1.permute(1,2,0) # 첫번쨰자리에 3번 자리 두번째 자리에 2번 자리, 세번째 0번자리 넣어줘.)
print(f't22.shape => {t22.shape}, {t22.ndim}D')

t22.shape => torch.Size([3, 2, 1]), 3D


In [23]:
print(f't1.data_ptr() => {t1.data_ptr()}, \nt11.data_ptr() => {t11.data_ptr()}, \nt22.data_ptr() => {t22.data_ptr()}')

t1.data_ptr() => 2729497858752, 
t11.data_ptr() => 2729497858752, 
t22.data_ptr() => 2729497858752
