### 텐서 연결 & 결합

In [1]:
# 모듈 로딩
import torch

In [20]:
# 텐서 데이터 생성 
torch.manual_seed(12)

# 임의의 0.<=~<1. 실수
x=torch.rand(2,10)

# 임의의 정수 : low<= ~ < high
y=torch.randint(0,2, (10,))
y2=torch.randint(0,2, (2, 10))

In [21]:
print(y2)
print(x)

tensor([[1, 1, 0, 1, 1, 0, 0, 0, 0, 0],
        [0, 0, 1, 1, 1, 1, 0, 0, 0, 0]])
tensor([[0.4657, 0.2328, 0.4527, 0.5871, 0.4086, 0.1272, 0.6373, 0.2421, 0.7312,
         0.7224],
        [0.1992, 0.6948, 0.5830, 0.6318, 0.5559, 0.1262, 0.9790, 0.8443, 0.1256,
         0.4456]])


In [18]:
print(f'x=> {x.shape}, {x.ndim}D') 
print(f'y=> {y.shape}, {y.ndim}D') 
print(f'y=> {y2.shape}, {y2.ndim}D') 

x=> torch.Size([2, 10]), 2D
y=> torch.Size([10]), 1D
y=> torch.Size([2, 10]), 2D


In [26]:
# tensor 연결 cat([텐서1, 텐서2 ...])
xy1 = torch.cat([x, y2], dim=0) 
print(f'xy1=>{xy1.shape}, {xy1.ndim}D')


xy1=>torch.Size([4, 10]), 2D


In [27]:
xy1.max(dim=0)

torch.return_types.max(
values=tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 0.9790, 0.8443, 0.7312,
        0.7224]),
indices=tensor([2, 2, 3, 2, 2, 3, 1, 1, 0, 0]))

In [37]:
# 행 단위의 최댓값 및 최댓값의 인덱스
maxValue = xy1.max(dim=1)[0] # 최댓값
maxIndex = xy1.max(dim=1)[1] # 최댓값의 인덱스
maxValue, maxIndex

(tensor([0.7312, 0.9790, 1.0000, 1.0000]), tensor([8, 6, 0, 2]))

In [39]:
# 열 단위의 최댓값 및 최댓값의 인덱스
maxValue = xy1.max(dim=0)[0] # 최댓값
maxIndex = xy1.max(dim=0)[1] # 최댓값의 인덱스
maxValue, maxIndex

(tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 0.9790, 0.8443, 0.7312,
         0.7224]),
 tensor([2, 2, 3, 2, 2, 3, 1, 1, 0, 0]))

In [45]:
import pandas as pd
data = pd.DataFrame({'A':[10, 11], 'B':[20,22], 'C':[30,33]})
data

A   B   C
0  10  20  30
1  11  22  33

In [50]:
data.max(), data.max(axis=1) # axis=1 로 하면 해당 행에서 가장 큰 값을 찾아줌. 집계함수는 다 이모냥으로 돌아간다.

(A    11
 B    22
 C    33
 dtype: int64,
 0    30
 1    33
 dtype: int64)