DNN MODEL => Layer + AF(activation function)

- layer 입력층 full connected Layer 즉 Linear
- layer 은닉층
- layer 은닉층

...                ===> 2개 이상 (Deep Neuron Network)

- layer 은닉층
- layer 출력층


<hr> 
CNN MODEL => Layer + AF(활성화 함수) 이미지 처리 --- 수요일에 배울 내용

- layer 입력층 convalution Layer + pooling layer
- layer 은닉층 convalution Layer + pooling layer
- layer 은닉층 convalution Layer + pooling layer
- => 이미지 형태 그대로 사용.

- layer 은닉층
- layer 출력층
- => 이미지 1D



<hr>
RNN MODEL

- layer 입력층 Embedding Layer
- layer 은닉층 convalution 1D layer
- layer 은닉층 RNN/LSTM layer
- => 텍스트 / 음성

- layer 은닉층
- layer 출력층

= 층만 바꾸면 된다는데...난 잘 모르겠고...

<hr>

overfitting
- Train Dataset 늘리기 => 쉽지 않음. 비용, 인력.
- feature의 개수 줄이기 => 저차원
- regulaization 규제 term 추가
- Dropout Layer 추가

nn.Dropout Layer
- 동작 : 일부 노드/퍼셉트론 무작위 비활성화
- 효과 : Overfitting 방지

매번 다른 형태 노드 학습 진행 >>> 성능 향상

dropout 기능 --> 학습 시 과대적합 해결하려고 쓰는 건데 평가할 때는 안됨..!
- 모델에 과대적합 나오면 이것부터 씀.

CLASS torch.nn.Dropout( p=0.5, inplace=False )

- 훈련 중 확률 사용하여 입력 텐서의 일부 요소를 무작위로 0으로 설정
- 연산 진행 되지 않음
- 매개변수
• p : Layer 내 노드/퍼셉트론이 0이 될 확률 [ 기본값: 0.5 ]



self.dropout = nn.Dropout(0.3)
<hr>

Gradient Vanishing & Exploding

In [34]:
# 해결방법 : 가중치 초기화 (Weight initialization = 세비어(Xavier) / 글로럿(Glorot)) 
import torch
import torch.nn as nn

class Net(nn.Module) :

    # 모델 구성 요소 생성 및 구조 설정
    def __init__(self) : 
        super(Net, self).__init__() # super 안에 자식클래스 이름과 self는 생략 가능.

        self.fc1 = nn.Linear(8,4) # fc1 = layer1
        self.fc2 = nn.Linear(4,2)
        self.fc3 = nn.Linear(2,1)
    
    # 순방향 학습 진행 함수
    def forword(self, x) :
        return self.fc3(self.fc2(self.fc1(x)))


In [37]:
import torch
import torch.nn as nn
from torchinfo import summary
import torchviz

In [39]:
# 모델 인스턴스 생성
model=Net()

print(model)

summary(model)

# w + b
# 8 + 1
# 8 + 1
# 8 + 1
# 8 + 1
# ===> total 36

# 4 + 1
# 4 + 1
# ===> total 10

# 2 + 1
# ===> total 3


Net(
  (fc1): Linear(in_features=8, out_features=4, bias=True)
  (fc2): Linear(in_features=4, out_features=2, bias=True)
  (fc3): Linear(in_features=2, out_features=1, bias=True)
)


Layer (type:depth-idx)                   Param #
Net                                      --
├─Linear: 1-1                            36
├─Linear: 1-2                            10
├─Linear: 1-3                            3
Total params: 49
Trainable params: 49
Non-trainable params: 0

In [ ]:
# 모델 인스턴스 속성
# 모델의 특정 층 추출
model.fc1.weight, model.fc1.bias

(Parameter containing:
 tensor([[-0.2321,  0.0932, -0.3271,  0.2081,  0.1896, -0.1728, -0.1957, -0.1939],
         [-0.1712, -0.0751, -0.3102,  0.3185, -0.0249, -0.2731, -0.1012,  0.0694],
         [ 0.2828, -0.2533, -0.0794,  0.0841,  0.1798, -0.3171,  0.2283,  0.1826],
         [-0.3300,  0.1637, -0.3419, -0.1940, -0.2468, -0.0697,  0.0056,  0.0754]],
        requires_grad=True),
 Parameter containing:
 tensor([-0.3278,  0.0250,  0.1161,  0.3358], requires_grad=True))

In [ ]:
# 모델의 각 층별 w, b 텐서 정보 확인
for param in model.parameters() :
    print(param, end='\n\n')

Parameter containing:
tensor([[-0.2321,  0.0932, -0.3271,  0.2081,  0.1896, -0.1728, -0.1957, -0.1939],
        [-0.1712, -0.0751, -0.3102,  0.3185, -0.0249, -0.2731, -0.1012,  0.0694],
        [ 0.2828, -0.2533, -0.0794,  0.0841,  0.1798, -0.3171,  0.2283,  0.1826],
        [-0.3300,  0.1637, -0.3419, -0.1940, -0.2468, -0.0697,  0.0056,  0.0754]],
       requires_grad=True)

Parameter containing:
tensor([-0.3278,  0.0250,  0.1161,  0.3358], requires_grad=True)

Parameter containing:
tensor([[ 0.2659, -0.2018, -0.1910,  0.3859],
        [ 0.2206,  0.1302,  0.1158, -0.0640]], requires_grad=True)

Parameter containing:
tensor([0.2435, 0.4871], requires_grad=True)

Parameter containing:
tensor([[0.6310, 0.4295]], requires_grad=True)

Parameter containing:
tensor([0.0871], requires_grad=True)



In [ ]:
for param in model.named_parameters() :
    print(param, end='\n\n')

('fc1.weight', Parameter containing:
tensor([[-0.2321,  0.0932, -0.3271,  0.2081,  0.1896, -0.1728, -0.1957, -0.1939],
        [-0.1712, -0.0751, -0.3102,  0.3185, -0.0249, -0.2731, -0.1012,  0.0694],
        [ 0.2828, -0.2533, -0.0794,  0.0841,  0.1798, -0.3171,  0.2283,  0.1826],
        [-0.3300,  0.1637, -0.3419, -0.1940, -0.2468, -0.0697,  0.0056,  0.0754]],
       requires_grad=True))

('fc1.bias', Parameter containing:
tensor([-0.3278,  0.0250,  0.1161,  0.3358], requires_grad=True))

('fc2.weight', Parameter containing:
tensor([[ 0.2659, -0.2018, -0.1910,  0.3859],
        [ 0.2206,  0.1302,  0.1158, -0.0640]], requires_grad=True))

('fc2.bias', Parameter containing:
tensor([0.2435, 0.4871], requires_grad=True))

('fc3.weight', Parameter containing:
tensor([[0.6310, 0.4295]], requires_grad=True))

('fc3.bias', Parameter containing:
tensor([0.0871], requires_grad=True))



In [ ]:
# 모델 구성하는 모든 layer 가져오기

for child in model.children() :
    print(child, end='\n\n')

for child in model.named_children() :
    print(child, end='\n\n')

Linear(in_features=8, out_features=4, bias=True)

Linear(in_features=4, out_features=2, bias=True)

Linear(in_features=2, out_features=1, bias=True)

('fc1', Linear(in_features=8, out_features=4, bias=True))

('fc2', Linear(in_features=4, out_features=2, bias=True))

('fc3', Linear(in_features=2, out_features=1, bias=True))



- Layer의 가중치 설정

In [ ]:
# 세비어 알고리즘의 가중치 초기화
nn.init.xavier_uniform_(model.fc1.weight)

Parameter containing:
tensor([[-0.4136,  0.1569,  0.1981,  0.2164,  0.2535,  0.3027, -0.2740,  0.2569],
        [-0.4111,  0.4686,  0.2546, -0.2410,  0.4218, -0.5349, -0.0713,  0.1359],
        [ 0.4340,  0.6735, -0.0613, -0.2331,  0.6571, -0.3274, -0.3752,  0.5281],
        [ 0.2872, -0.5828, -0.0871, -0.1526, -0.4463, -0.1522,  0.4270,  0.1775]],
       requires_grad=True)

In [ ]:
# 헤 알고리즘의 가중치 초기화
nn.init.kaiming_normal_(model.fc1.weight)

Parameter containing:
tensor([[ 0.0419, -0.6099,  0.1906, -0.4992,  0.6398,  0.4509,  0.4221,  1.1307],
        [ 0.2579, -0.2435,  0.7617, -0.5576, -0.6433,  0.8052,  0.6637, -0.4314],
        [ 0.3286, -0.0411, -0.1039, -0.7153,  0.0186, -0.3355,  0.2184, -1.2126],
        [ 0.4627,  0.0273,  1.3195, -0.5464,  0.5824, -0.2040, -0.4065, -0.1575]],
       requires_grad=True)

In [ ]:
# 전체 layer에 대하여 xavier uniform initialization 설정
for name, child in model.named_children() :
    nn.init.xavier_uniform_(child.weight)