In [2]:
# 모듈 로딩
from PIL import Image
import torchvision.transforms as transforms

In [7]:
## 이미지 데이터 로딩
file = '../data/image/xuguanghan.jpg'

In [8]:
catImg = Image.open(fp=file)
catImg.format, catImg.height, catImg.width, catImg.mode, type(catImg)

('JPEG', 574, 550, 'RGB', PIL.JpegImagePlugin.JpegImageFile)

In [13]:
# 사용법 
# (1) 인스턴스 생성 
to_tensor = transforms.ToTensor()

# (2) 인스턴스변수 사용
catTS = to_tensor(catImg)

# (3) 변환된 이미지 텐서 확인
print(catTS.shape, catTS.ndim)
print(catTS[0])

torch.Size([3, 574, 550]) 3
tensor([[0.6667, 0.6824, 0.6980,  ..., 0.4039, 0.4392, 0.4667],
        [0.6745, 0.6863, 0.6902,  ..., 0.3961, 0.4235, 0.4431],
        [0.6745, 0.6824, 0.6902,  ..., 0.4118, 0.4431, 0.4627],
        ...,
        [1.0000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000]])


In [21]:
## open cv
import cv2
img = cv2.imread(filename=file) # BGR
img2 = cv2.cvtColor(img, cv2.COLOR_BGR2RGB) # RGB

print(type(img), img.shape, img.ndim)
print(type(img2), img2.shape, img2.ndim)

## 텐서화
cat2 = to_tensor(img)
cat3 = to_tensor(img2)

print(cat2.shape, cat2.ndim)
print(cat2[0])
print()
print(cat3.shape, cat3.ndim)
print(cat3[0])

<class 'numpy.ndarray'> (574, 550, 3) 3
<class 'numpy.ndarray'> (574, 550, 3) 3
torch.Size([3, 574, 550]) 3
tensor([[0.7647, 0.7804, 0.7961,  ..., 0.4510, 0.4863, 0.5137],
        [0.7725, 0.7843, 0.7882,  ..., 0.4431, 0.4706, 0.4902],
        [0.7725, 0.7804, 0.7882,  ..., 0.4549, 0.4863, 0.5059],
        ...,
        [1.0000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000],
        [0.9922, 0.9922, 0.9922,  ..., 1.0000, 1.0000, 1.0000],
        [0.9922, 0.9922, 0.9922,  ..., 1.0000, 1.0000, 1.0000]])

torch.Size([3, 574, 550]) 3
tensor([[0.6667, 0.6824, 0.6980,  ..., 0.4039, 0.4392, 0.4667],
        [0.6745, 0.6863, 0.6902,  ..., 0.3961, 0.4235, 0.4431],
        [0.6745, 0.6824, 0.6902,  ..., 0.4157, 0.4471, 0.4667],
        ...,
        [1.0000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000]])


In [17]:
# Resizing
resize = transforms.Resize()
resize((50,50))


<class 'numpy.ndarray'> (574, 550, 3) 3


In [49]:
preprocessing = transforms.Compose(
    [transforms.Resize(size=(50,50)), # 넘파이 안됨..
    transforms.RandomHorizontalFlip(p=0.5), # 원하는 만큼 돌려놓기.
    transforms.ToTensor()]
)

In [50]:
preprocessing(catImg)

tensor([[[0.7294, 0.7961, 0.8196,  ..., 0.5216, 0.5020, 0.4471],
         [0.7294, 0.8000, 0.8196,  ..., 0.6118, 0.6196, 0.6235],
         [0.7294, 0.7961, 0.8196,  ..., 0.6706, 0.6706, 0.6706],
         ...,
         [0.7333, 0.7882, 0.8000,  ..., 0.8588, 0.7608, 0.7843],
         [0.7843, 0.8275, 0.8392,  ..., 0.9059, 0.8235, 0.8157],
         [0.9725, 0.9804, 0.9804,  ..., 0.9882, 0.9804, 0.9804]],

        [[0.7333, 0.8039, 0.8275,  ..., 0.5176, 0.4941, 0.4353],
         [0.7333, 0.8039, 0.8275,  ..., 0.6118, 0.6196, 0.6196],
         [0.7373, 0.8000, 0.8275,  ..., 0.6745, 0.6706, 0.6667],
         ...,
         [0.7412, 0.7922, 0.8078,  ..., 0.8588, 0.7686, 0.7843],
         [0.7882, 0.8314, 0.8392,  ..., 0.9020, 0.8275, 0.8196],
         [0.9765, 0.9804, 0.9804,  ..., 0.9882, 0.9804, 0.9804]],

        [[0.8235, 0.8667, 0.8784,  ..., 0.5647, 0.5373, 0.4784],
         [0.8235, 0.8706, 0.8824,  ..., 0.6667, 0.6824, 0.6824],
         [0.8235, 0.8706, 0.8824,  ..., 0.7490, 0.7373, 0.

#### 이미지 데이터 셋 <hr>
- torchvision.ImageFolder 클래스 사용
   * 이미지 데이터 라벨링
   * 이미지 데이터 전처리


In [26]:
from torchvision.datasets import ImageFolder

In [43]:
img_root = '../data/image/'

In [44]:
imgDS = ImageFolder(root=img_root,
            transform = preprocessing)

In [45]:
imgDS.classes, imgDS.class_to_idx, imgDS.imgs

(['afolder'], {'afolder': 0}, [('../data/image/afolder\\gray_angry.jpg', 0)])

In [51]:
from torch.utils.data import DataLoader
imgDL=DataLoader(imgDS)

for (img, label) in imgDL :
    print(img.shape, label.shape, label)
    break

torch.Size([1, 3, 50, 50]) torch.Size([1]) tensor([0])


In [ ]:
# 원하는 이미지 