###  Logistic Regression
---
- 둘 중 하나를 결정하는 문제 = 이진 분류(Binary Classification)
- Regression이지만 분류인 이유
    * => 선형 가설(y=wx+b)에 기반하여 분류하기때문에 Regression이라함
- 이진 분류(Binary Classification)
    * 0과 1로 결과가 나오는 분류
    * 기존 LinearRegression의 선형함수만으로는 해당 S곡선 불가
    * 0과 1 두 가지로 분류해주는 특별한 함수 필요 ==> 활성화함수(Activation Function)
        - $ y=Wx+b $ ===> $ y=f(Wx+b)
        - Sigmoid Function  
        
    * 비용 함수(Cost Function)
        - 최적의 모델 파라미터를 찾을 수 있는 비용 함수(cost function) 정의
        - torch.nn.functional의 binary_cross_entropy(예측값, 실제값)

In [2]:
# 모듈 로딩
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [3]:
# 랜덤 시드 설정 
torch.manual_seed(1)

In [4]:
# 훈련 데이터
x_data = [[1, 2], [2, 3], [3, 1], [4, 3], [5, 3], [6, 2]] # 6X2
y_data = [[0], [0], [0], [1], [1], [1]] # 6X1
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)
x_train, y_train

(tensor([[1., 2.],
         [2., 3.],
         [3., 1.],
         [4., 3.],
         [5., 3.],
         [6., 2.]]),
 tensor([[0.],
         [0.],
         [0.],
         [1.],
         [1.],
         [1.]]))

In [5]:
# 모델 설계
# Sequential : 순서대로 진행되어야 하는 모듈을 묶음으로 관리.
# (순서를 갖고 있는 모듈 컨테이너. 정의된 순서로 모든 모듈들을 통해 데이터 전달)
# (여러 개의 레이어를 순차적으로 쌓아서 모델을 만들 수 있도록 한다.)

model = nn.Sequential(
   nn.Linear(2, 1), # input_dim = 2, output_dim = 1 # w를 얘가 갖고 있음. 직접 만드는 것 X 
   nn.Sigmoid()     # 출력은 시그모이드 함수 거침 (★ 순서 중요! Linear 하는 결과가 Sigmoid에 들어가야함. 이진 분류라서 사용하는 것!)
)

# optimizer 설정
# 확률적 경사 하강법으로 업데이트 해야하는 w,b는 모델 인스턴스에서 가지고 있음.
# => 가지고 오는 메서드 = model.parameters()
optimizer = optim.SGD(model.parameters(), lr=1) 

In [6]:
# 학습

def training():
    nb_epochs = 1000 # 1000번 학습
    for epoch in range(nb_epochs + 1):
        # 예측값 H(x) 계산
        hypothesis = model(x_train) #훈련 데이터를 사용하여 모델의 예측값을 계산

        # cost 계산 => 이진 분류 손실함수  binary_cross_entropy()
        # y=0일 때 오차, y=1일 때 오차를 각각 계산.
        cost = F.binary_cross_entropy(hypothesis, y_train)

        # cost로 W,b값 업데이트 => SGD 경사하강법 방식으로 업데이트 진행 ---- 사실 경사하강법 이해 아직 못했음.
        optimizer.zero_grad() # 초기화
        cost.backward() # 역전파 : 손실 함수를 미분하여 모델의 파라미터에 대한 기울기(그래디언트)를 계산
        optimizer.step() # 옵티마이저에 지정된 학습률(lr=0.1)에 따라 모델의 파라미터를 업데이트

        # 10회마다 로그 출력
        if epoch % 10 == 0:
            prediction = hypothesis >= torch.FloatTensor([0.5])  # 예측값이 0.5를 넘으면 True로 간주
            correct_prediction = prediction.float() == y_train # 정답 = 실제값(y_train)과 일치하는 경우만 True로 간주
            accuracy = correct_prediction.sum().item() / len(correct_prediction) # 정확도 = 정답 값의 합계 / 정답의 개수

            print(f'Epoch {epoch:4d}/{nb_epochs} Cost: {cost.item():.6f} Accuracy {accuracy * 100:2.2f}%')
            # 현재 학습횟수 / 전체 학습 횟수   cost : 손실함수 값    Accuracy : 정확도(백분율로 출력)

In [7]:
training()

Epoch    0/1000 Cost: 0.539713 Accuracy 83.33%
Epoch   10/1000 Cost: 0.614853 Accuracy 66.67%
Epoch   20/1000 Cost: 0.441875 Accuracy 66.67%
Epoch   30/1000 Cost: 0.373145 Accuracy 83.33%
Epoch   40/1000 Cost: 0.316358 Accuracy 83.33%
Epoch   50/1000 Cost: 0.266094 Accuracy 83.33%
Epoch   60/1000 Cost: 0.220498 Accuracy 100.00%
Epoch   70/1000 Cost: 0.182095 Accuracy 100.00%
Epoch   80/1000 Cost: 0.157299 Accuracy 100.00%
Epoch   90/1000 Cost: 0.144091 Accuracy 100.00%
Epoch  100/1000 Cost: 0.134272 Accuracy 100.00%
Epoch  110/1000 Cost: 0.125769 Accuracy 100.00%
Epoch  120/1000 Cost: 0.118297 Accuracy 100.00%
Epoch  130/1000 Cost: 0.111680 Accuracy 100.00%
Epoch  140/1000 Cost: 0.105779 Accuracy 100.00%
Epoch  150/1000 Cost: 0.100483 Accuracy 100.00%
Epoch  160/1000 Cost: 0.095704 Accuracy 100.00%
Epoch  170/1000 Cost: 0.091369 Accuracy 100.00%
Epoch  180/1000 Cost: 0.087420 Accuracy 100.00%
Epoch  190/1000 Cost: 0.083805 Accuracy 100.00%
Epoch  200/1000 Cost: 0.080486 Accuracy 100.00

In [8]:

print(list(model.parameters())) 
#모델 내의 모든 학습 가능한 파라미터가 리스트 형태로 출력
#각 파라미터는 해당하는 레이어의 가중치(weight)와 편향(bias)로 구성
# 이러한 파라미터들은 모델의 학습 과정에서 경사 하강법 등의 최적화 알고리즘을 사용하여 업데이트


# 첫번째 파라미터 : tensor([[3.2477, 1.5151]], requires_grad=True) ==> 가중치
# 두번째 파라미터 : tensor([-14.4576], requires_grad=True) ==> 편향(bias)

[Parameter containing:
tensor([[3.2534, 1.5181]], requires_grad=True), Parameter containing:
tensor([-14.4839], requires_grad=True)]
