### [Pytorch기반 선형회귀] <hr>

- [1] 모듈 로딩 및 데이터 준비 <hr>

In [1]:
import torch                            # 파이토치 텐서 및 기본 함수들 관련 모듈
import torch.nn as nn                   # 인공신경망 층 관련 모듈
import torch.nn.functional as F         # 인공신경망 관련 함수들 모듈
import torch.optim as optim             # 인공신경망 최적화 관련 모듈

In [2]:
# 랜덤 시드 설정
torch.manual_seed(1)

In [3]:
# 데이터 준비
Xtrn = torch.FloatTensor([[1], [2], [3]]) # 1 X 3
ytrn = torch.FloatTensor([[2], [4], [6]]) # 1 X 3

In [4]:
# 데이터 확인 
print(f'[Xtrain] \n{Xtrn}\nXtrain.shape : {Xtrn.shape}\tXtrain.ndim : {Xtrn.ndim}\n')
print(f'[ytrain] \n{ytrn}\nytrain.shape : {ytrn.shape}\tytrain.ndim : {ytrn.ndim}')

[Xtrain] 
tensor([[1.],
        [2.],
        [3.]])
Xtrain.shape : torch.Size([3, 1])	Xtrain.ndim : 2

[ytrain] 
tensor([[2.],
        [4.],
        [6.]])
ytrain.shape : torch.Size([3, 1])	ytrain.ndim : 2


- [2] 학습 위한 준비 <hr>

In [5]:
# 가중치 및 절편 데이터 생성 및 초기화
# - 가중치 W            : 0으로 초기화하고 학습 통해 값이 변경된다.
# - requires_grad=True : 학습을 통해 계속 값이 변경되는 변수.
# - torch.zeros(텐서 원소 개수)

w = torch.zeros(1, requires_grad=True) # 크기가 1인 텐서 생성.
b = torch.zeros(1, requires_grad=True) # requires_grad = 연산 그래프에서 기울기를 추적해야 함

# 역전파(backpropagation) 과정에서 해당 파라미터에 대한 기울기를 계산하는 데 사용됩니다.

# 가중치(w)와 편향(b)을 모두 0으로 초기화

In [18]:
# 경사하강법 설정 : w,b 업데이트 
# w, b 변수, 학습률 지정
optimizer = optim.SGD([w, b], lr=0.01)

학습률(lr) : 
- 각 반복 단계에서 모델 파라미터를 조정하는 양을 결정하는 하이퍼파라미터
- 모델이 수렴할 수 있는 속도와 정확도를 결정

학습률 高 :
- 매개변수 업데이트가 크게 이루어지므로 학습 속도가 빨라짐.
- 최적값을 찾지 못할 수 있음.
- 수렴 불안정

학습률 低 :
- 매개변수 업데이트가 작게 이루어지므로 학습이 안정적으로 진행
- 최적값에 수렴하는 데 시간이 오래 걸릴 수 있음.

- [3] 학습 진행 <hr>

In [19]:
# 학습 진행
# - 에포크 : 처음부터 ~ 끝까지 학습하는 것 의미 

nb_epochs = 100                 # 100번 학습

for epoch in range(nb_epochs + 1):
    # 예측값 H(x) 계산 ! H(x) = wx + b
    # w = 가중치, x = 입력데이터, b = 편향

    y_pred = w * Xtrn + b

    # cost 계산 = 합((예측값 - 정답 ) **2 ) ---> 평균제곱오차 MSE
    cost = torch.mean((y_pred - ytrn) ** 2) 
    # 선형회귀 모델일 떄는 평균 제곱 오차(MSE)
    # 분류 모델일 때는 Cross Entropy Error, log loss를 사용.

    # cost로 H(x) 개선 - 최적화 단계.
    optimizer.zero_grad()           # gradient 0으로 초기화
    cost.backward()                 # 비용 함수 미분하여 gradient 계산
    print(f'수식을 w로 미분한 값 : {w.grad}')

    optimizer.step()                # step => W, b 업데이트
    print(f'업데이트 된 w : {w.grad}, b : {b.grad}')

    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print(f'Epoch {epoch:4d}/{nb_epochs} W: {w.item():.3f}, b: {b.item():.3f} Cost: {cost.item():.6f}')
    

수식을 w로 미분한 값 : tensor([-0.0376])
업데이트 된 w : tensor([-0.0376]), b : tensor([0.0855])
Epoch    0/100 W: 1.844, b: 0.355 Cost: 0.018130
수식을 w로 미분한 값 : tensor([-0.0375])
업데이트 된 w : tensor([-0.0375]), b : tensor([0.0853])
수식을 w로 미분한 값 : tensor([-0.0374])
업데이트 된 w : tensor([-0.0374]), b : tensor([0.0850])
수식을 w로 미분한 값 : tensor([-0.0373])
업데이트 된 w : tensor([-0.0373]), b : tensor([0.0848])
수식을 w로 미분한 값 : tensor([-0.0372])
업데이트 된 w : tensor([-0.0372]), b : tensor([0.0846])
수식을 w로 미분한 값 : tensor([-0.0371])
업데이트 된 w : tensor([-0.0371]), b : tensor([0.0844])
수식을 w로 미분한 값 : tensor([-0.0371])
업데이트 된 w : tensor([-0.0371]), b : tensor([0.0842])
수식을 w로 미분한 값 : tensor([-0.0370])
업데이트 된 w : tensor([-0.0370]), b : tensor([0.0840])
수식을 w로 미분한 값 : tensor([-0.0369])
업데이트 된 w : tensor([-0.0369]), b : tensor([0.0838])
수식을 w로 미분한 값 : tensor([-0.0368])
업데이트 된 w : tensor([-0.0368]), b : tensor([0.0836])
수식을 w로 미분한 값 : tensor([-0.0367])
업데이트 된 w : tensor([-0.0367]), b : tensor([0.0834])
수식을 w로 미분한 값 : tensor([-0.0

[4] 학습 후 모델 파라미터 확인 <hr>

In [20]:
w, b

(tensor([1.8774], requires_grad=True), tensor([0.2788], requires_grad=True))

In [21]:
# 학습 완료 후의 w, b 텐서 값 확인 
w.item(), b.item() # 값만 빼오고 싶을 때는 .item() 메서드 사용.

(1.8773620128631592, 0.27878478169441223)

[5] 예측 <hr>

In [9]:
### ===> x값 넣고 y값 확인
pre_y = w*3+b
pre_y.item()

5.815145969390869

pre_y = w*3 + b :
- 주어진 가중치 w와 편향 b를 사용하여 예측값 'pre_y'를 계산
- 선형 회귀 모델에서는 입력 변수 'x'와 가중치 'w'를 곱하고 편향 b를 더하여 예측값을 계산
- 여기서 *3은 입력 변수를 3으로 곱하는 것을 의미

pre_y.item() : 
- 계산된 예측값 'pre_y'를 스칼라 값으로 변환하여 반환
- 이렇게 함으로써 텐서에서 스칼라 값을 추출