### 다중분류(Multi-Class Classification)
---
- 3 개 이상의 답 중 1개를 고르는 경우
- 비용함수(Cost Function)  => Cross Entropy
    * 이진 교차 엔트로피(Binary Cross Entropy)와 유사한 방식으로 계산

In [2]:
# 모듈 로딩
import torch
import torch.nn.functional as F

In [3]:
# 랜덤 시드 설정
torch.manual_seed(1)

In [4]:
# 데이터 생성
z = torch.FloatTensor([1, 2, 3])
print(z.shape, f'{z.ndim}차원', z)

torch.Size([3]) 1차원 tensor([1., 2., 3.])


In [5]:
# 소프트맥스 함수 적용
# F.softmax(텐서, dim=softmax를 수행할 차원)
hypothesis = F.softmax(z, dim=0) # dim=0 : 소프트맥스를 계산할 차원을 지정(여기서는 0번째 차원을 기준 / 소프트맥스 계산 )
print(hypothesis, hypothesis.sum()) # 소프트맥스 함수를 적용한 결과인 hypothesis와 그 합을 계산하여 출력


# 소프트맥스 함수는 각 클래스에 대한 확률을 계산
# 이 확률은 0부터 1 사이의 값으로 정규화되기 때문에 소프트맥스 함수를 적용한 결과의 모든 요소를 합하면 => 1

tensor([0.0900, 0.2447, 0.6652]) tensor(1.)


In [6]:
z2 = torch.rand(3, 5, requires_grad=True) # ( 무작위의 실수가 들어있는 3 X 5 행렬 )
print(z2.shape, f'{z2.ndim}차원', z2, sep='\n')

torch.Size([3, 5])
2차원
tensor([[0.7576, 0.2793, 0.4031, 0.7347, 0.0293],
        [0.7999, 0.3971, 0.7544, 0.5695, 0.4388],
        [0.6387, 0.5247, 0.6826, 0.3051, 0.4635]], requires_grad=True)


torch.rand
- 주어진 모양에 맞는 텐서를 만들고, 그 텐서의 각 요소에 대해 0과 1 사이의 무작위한 값을 할당
- requires_grad = True : 기울기 계산. ( 텐서를 사용하여 역전파 과정을 수행 )

In [9]:
# dim=1 ==> (3, 5)에서 5가지에 대한 값 

hypothesis = F.softmax(z2, dim=1) # 예측 확률을 계산.  dim =1 이므로 1번째 차원을 기준으로 소프트맥스를 계산

print(hypothesis, hypothesis.sum())
#소프트맥스 함수를 적용한 결과인 hypothesis와 그 각각의 합을 계산하여 출력 (행별로 1 + 1 + 1)

tensor([[0.2645, 0.1639, 0.1855, 0.2585, 0.1277],
        [0.2430, 0.1624, 0.2322, 0.1930, 0.1694],
        [0.2226, 0.1986, 0.2326, 0.1594, 0.1868]], grad_fn=<SoftmaxBackward0>) tensor(3.0000, grad_fn=<SumBackward0>)


### One-Hot-Encoding
- squeeze() / unsqueeze() 살펴보기