In [1]:
## 모듈 로딩
import numpy as np

In [6]:
## ndarray 타입 데이터 생성

# 0으로 채워진 ndarray 객체 생성 ==> zeros()
np.zeros(2) # default = flaot64

array([0., 0.])

In [8]:
np.zeros((2,3), dtype=np.int8)

array([[0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [9]:
# 1로 채워진 ndarrary 객체 생성 ==> ones()
np.ones(10), np.ones(10, dtype = np.int32), np.ones((2,5), dtype=np.bool_)

(array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 array([[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]))

In [11]:
# 랜덤 데이터로 ndarrary 객체 생성 ==> random
np.random.randint(1, 5, (3, 10)) # low <= n < high 예) 3부터 10까지

array([[2, 4, 3, 3, 1, 3, 3, 3, 4, 2],
       [3, 2, 2, 2, 2, 3, 4, 2, 2, 2],
       [3, 4, 1, 3, 4, 4, 4, 2, 1, 3]])

In [14]:
np.random.rand(5,2) # 0에서 1까지 (0은 포함, 1은 미포함)

array([[0.12383306, 0.97800617],
       [0.73677612, 0.23615197],
       [0.66816482, 0.77378475],
       [0.46781328, 0.42077006],
       [0.1760689 , 0.27298698]])

In [20]:
np.random.randn(5), np.random.randn(1,2,3)

(array([ 1.58248112, -0.9092324 , -0.59163666,  0.18760323, -0.32986996]),
 array([[[-1.19276461, -0.20487651, -0.35882895],
         [ 0.6034716 , -1.66478853, -0.70017904]]]))

In [21]:
# 랜덤 고정
np.random.seed(5)
np.random.randn(5)

array([ 0.44122749, -0.33087015,  2.43077119, -0.25209213,  0.10960984])

In [35]:
data = np.random.randn(10)
print(data)



[-1.23056871  2.02032342  0.27085958  0.95892656 -0.82765618 -0.57185239
  0.28532125 -0.28890779 -0.73697211  0.48577995]


In [32]:
np.random.shuffle(data) # 랜덤 셔플로 돌릴 때 마다 섞임.
print(data)

[-0.21017082  0.40226978 -0.05558717 -2.4005372   0.21319905 -0.73668102
 -0.28415804  2.66504906 -0.11209336 -0.28873899]


In [29]:
data.sum(), data.max(), data.min()

(-1.7552296614216083, 1.7363036330376642, -1.2435850185549626)

In [27]:
data.argmax(), data.argmin() # 인덱스

(6, 9)

In [40]:
np.random.seed(5)
data = np.random.randint(2,7, (2,3))
print(data)
data.sum()

[[5 2 3]
 [2 6 5]]


23