### 인공신경망 모델 클래스 만들기 <hr>
- 부모 클래스 : nn.Module 상속
- 필수 오버라이딩 메서드 : __init__(), forward()

[1] 모듈 로딩 <hr>

In [35]:
import torch
import torch.nn as nn

In [40]:
# 로지스틱 회귀 모델 클래스 생성.
# - Linear + Sigmoid
class LogicLinear(nn.Module) :
    # 모델 구조 설정
    def __init__(self, in_, out_):
        super().__init__() # 부모
        self.layer1 = nn.Linear(in_, 10) # in개 받아서 10개를 내 놓음
        self.sigmoid1 = nn.Sigmoid()
        self.layer2 = nn.Linear(10, out_) 
        self.sigmoid2 = nn.Sigmoid()
        

    # 순방향 학습 진행 콜백 함수
    def forward(self, x) :
        y = self.layer1(x)
        z = self.sigmoid1(y)
        y = self.layer2(z)
        z = self.sigmoid2(y)
        return z


In [41]:
#모델 인스턴스 생성
ll=LogicLinear(783, 3)
print(f'모델 구조 확인 ==== {ll}')

모델 구조 확인 ==== LogicLinear(
  (layer1): Linear(in_features=783, out_features=10, bias=True)
  (sigmoid1): Sigmoid()
  (layer2): Linear(in_features=10, out_features=3, bias=True)
  (sigmoid2): Sigmoid()
)


In [42]:
print('모델 구성 w, b ====')
for param in ll.parameters(): print(param)

모델 구성 w, b ====
Parameter containing:
tensor([[-1.2065e-02,  2.6134e-03,  2.4260e-02,  ...,  5.5660e-03,
          2.0949e-02,  2.8554e-02],
        [-2.3254e-02,  1.4174e-02,  1.6679e-03,  ..., -2.3070e-02,
          3.9350e-04,  7.2024e-03],
        [ 1.0918e-02,  1.4464e-04,  1.0877e-02,  ..., -3.2075e-06,
          2.4543e-02,  2.7993e-02],
        ...,
        [ 3.5498e-02, -2.3376e-02, -3.1041e-02,  ..., -3.4261e-02,
          1.6130e-02, -1.6929e-02],
        [ 3.5479e-02, -2.9226e-02, -1.6548e-03,  ..., -1.4011e-02,
          2.5693e-02,  1.7661e-02],
        [ 2.8841e-02,  2.8896e-02,  3.4934e-02,  ..., -8.0138e-03,
         -2.6245e-02, -9.0402e-03]], requires_grad=True)
Parameter containing:
tensor([ 0.0116, -0.0291,  0.0227, -0.0158, -0.0053,  0.0164,  0.0085,  0.0080,
         0.0267, -0.0350], requires_grad=True)
Parameter containing:
tensor([[ 0.1636,  0.2462, -0.0490, -0.2537,  0.1910, -0.1389, -0.2370,  0.2847,
         -0.0709,  0.1665],
        [ 0.3058, -0.0549, -0.