cv.imread(filename,[flags])
- filename : Name of ile to be loaded
- flags  

#### 기본적인 이미지 다루기

In [1]:
import cv2
import numpy as np              # 반환값이 numpy라서 로딩해야함.

[1] 이미지 데이터 로딩 <hr>
- 컬러 / 회색 이미지 변환 로딩 가능

In [3]:
file = 'C:/Users/KDP-48/PythonProject/Data/KDT-09-OpenCV/data/image/angry.jpg'

In [4]:
# 컬러 이미지 로딩
img_rgb = cv2.imread(file, cv2.IMREAD_COLOR)

# 회색 이미지 로딩
img_gray = cv2.imread(file, cv2.IMREAD_GRAYSCALE)

In [5]:
# 컬러 이미지 데이터 정보 확인
print(f'[COLOR IMAGE]')
print(f'SHAPE : {img_rgb.shape}     DIM : {img_rgb.ndim}D')
print(f'DTYPE : {img_rgb.dtype}     SIZE : {img_rgb.size}BYTE')
print()

# 회색 이미지 데이터 정보 확인
print(f'[COLOR IMAGE]')
print(f'SHAPE : {img_gray.shape}     DIM : {img_gray.ndim}D')
print(f'DTYPE : {img_gray.dtype}     SIZE : {img_gray.size}BYTE')

[COLOR IMAGE]
SHAPE : (384, 384, 3)     DIM : 3D
DTYPE : uint8     SIZE : 442368BYTE

[COLOR IMAGE]
SHAPE : (384, 384)     DIM : 2D
DTYPE : uint8     SIZE : 147456BYTE


In [6]:
# # 이미지 창 띄우기
# cv2.imshow('[COLOR]', img_rgb)

# # 이미지 창 제어
# cv2.waitKey()

# # 이미지 창 닫기
# cv2.destroyAllWindows()

In [7]:
# if img_rgb is not None :
#     cv2.imshow('[COLOR]', img_rgb)
#     while True :
#         # 이미지 창 제어    
#         key = cv2.waitKey()                 # 키 입력 대기
#         print(f'key => {key} - {hex(key)}') # 입력 키 출력

#         if key == 27 : # 엔터 키 => 13  # ESC 일 때 화면 종료
#             cv2.destroyAllWindows()
#             break

# else:
#     print('No image file!')

ret = cv2.imwrite(이미지 경로 포함 파일명, 데이터)

In [8]:
# 회색 이미지 로딩
img_gray = cv2.imread(file, cv2.IMREAD_GRAYSCALE)

save_filename = 'C:/Users/KDP-48/PythonProject/Data/KDT-09-OpenCV/data/image/gray_angry.jpg'
gray_file = cv2.imwrite(save_filename, img_gray) # 흑백 이미지 저장

multi_channel = cv2.split(image)

In [9]:
# 채널 이미지 분리
import time
# 컬러 이미지 로딩
img_rgb = cv2.imread(file, cv2.IMREAD_COLOR)

img_b, img_g, img_r = cv2.split(img_rgb)
#인덱스로도 분리 가능.
#b, g, r = img_rgb[:, :, 0], img_rgb[:, :, 1], img_rgb[:, :, 2]

cv2.imshow('[BLUE CHANNEL]', img_b)
cv2.waitKey(3000) # 3초 = 3000 --> 3초 후 자동 꺼짐
cv2.destroyAllWindows()

cv2.imshow('[GREEN CHANNEL]', img_g)
cv2.waitKey(3000) # 3초 = 3000 --> 3초 후 자동 꺼짐
cv2.destroyAllWindows()


cv2.imshow('[RED CHANNEL]', img_r)
cv2.waitKey(3000) # 3초 = 3000 --> 3초 후 자동 꺼짐
cv2.destroyAllWindows()

In [10]:
# 이미지 데이터 채널 병합/변경
img_rgb = cv2.imread(file, cv2.IMREAD_COLOR)

img_b, img_g, img_r = cv2.split(img_rgb)

img_rgb = cv2.merge((img_r, img_g, img_b)) #채널 순서 변경.

cv2.imshow('[RGB IMAGE]', img_rgb)
cv2.waitKey(4000)
cv2.destroyAllWindows()

In [11]:
# 이미지 채널 BGR ▶ HSV

img_rgb = cv2.imread(file, cv2.IMREAD_COLOR)

# BGR -> HSV
src_hsv = cv2.cvtColor(img_rgb, cv2.COLOR_BGR2HSV)
planes = cv2.split(src_hsv)

cv2.imshow('[HSV IMG]', src_hsv)
if cv2.waitKey() or cv2.getWindowProperty('[HSV IMG]', cv2.WND_PROP_VISIBLE) <1 : # 3초 = 3000 --> 3초 후 자동 꺼짐
    # 이미지 창 닫기
    cv2.destroyAllWindows()

In [12]:
# Matplotlib 등 3장 보기.

In [13]:
# 도화지 만들기
h, w = 500, 500

img_w=np.full((h, w), 255, dtype=np.uint8)
# ret = cv2.imwrite(file, img_w)
# ret

In [14]:
# 도화지 만들기
img = np.zeros((300, 300), dtype=np.uint8)
img.shape, img.ndim

# 흰 도화지 만들기
img_white = np.full((300, 300), 255, dtype=np.uint8)
img_white.shape, img_white.ndim

((300, 300), 2)

In [15]:
# 이미지 데이터에 그림 그리기
cv2.line(img, (10, 10), (70,70), (255,0,0))
print(img)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [16]:
# 화면에 출력
cv2.imshow('[BLACK]', img)
cv2.imshow('[WHITE]', img_white)
cv2.waitKey(3000)
cv2.destroyAllWindows()


In [17]:
# 이미지는 left 탑부터 값을 카운팅.
# 파란색 1px짜리 데이터 생성
cv2.line(img_rgb, (50, 50), (150, 50), (255, 0, 0), cv2.LINE_AA)
cv2.imshow('[COLOR]', img_rgb)
cv2.waitKey()
cv2.destroyAllWindows()

In [18]:
h, w = 500, 500

img_w=np.full((h, w), 255, dtype=np.uint8)
#cv2.imwrite(file, img_w)
cv2.rectangle(img_w, (500, 200), (1000, 400), (255, 0, 0), 5, cv2.LINE_8)
cv2.imshow('[RECTANGLE]', img_w)
cv2.waitKey()
cv2.destroyAllWindows()

In [19]:
cv2.circle(img_rgb, (300, 300), 50, (0,255,0), cv2.FILLED, cv2.LINE_4)
cv2.imshow('[CIRCLE]', img_rgb)
cv2.waitKey(4000)
cv2.destroyAllWindows()

In [20]:

cv2.ellipse(img_rgb, (50, 300), (50,75), 15, 0, 180, (0,255,2), 2)
cv2.imshow('[ellipse]', img_rgb)
cv2.waitKey(4000)
cv2.destroyAllWindows()

In [21]:
src = np.zeros((768, 1366, 3), dtype=np.uint8)

src = cv2.line(src, (100, 100), (1200, 100), (0, 0, 255), 3, cv2.LINE_AA)
src = cv2.circle(src, (300, 300), 50, (0, 255, 0), cv2.FILLED, cv2.LINE_4)
src = cv2.rectangle(src, (500, 200), (1000, 400), (255, 0, 0), 5, cv2.LINE_8)
src = cv2.ellipse(src, (1200, 300), (100, 50), 0, 90, 180, (255, 255, 0), 2)

In [22]:
pts1 =np.array([[100, 500], [300, 500], [200, 600]])
pts2 =np.array([[600, 500], [800, 500], [700,600]])
src = cv2.polylines(src, [pts1], True, (0, 255, 255), 2)
src = cv2.fillPoly(src, [pts2], (255, 0, 255), cv2.LINE_AA)
src = cv2.putText(src, "HAPPY", (900, 600), cv2.FONT_HERSHEY_COMPLEX, 2, (255, 255, 255), 3)

cv2.imshow('src', src)
cv2.waitKey()
cv2.destroyAllWindows()