### 선형 모델 동작 살펴보기
- nn.Linear 클래스
- y= wx+b 공식으로 동작하는 선형회귀모델

In [56]:
# 모듈 로딩
import torch                        # 텐서, 기본 함수들
import torch.nn as nn               # 인공신경망 관련
import torch.nn.functional as F        # 함수들

In [57]:
# 테스트용 임의의 데이터
data = torch.FloatTensor([[8,9], 
                          [6,6],
                          [3,4]])
target = torch.LongTensor([[17], [12], [7]])

data.shape, target.shape

(torch.Size([3, 2]), torch.Size([3, 1]))

In [58]:
# 선형모델 인스턴스 생성. => 각 입력 데이터의 피처 개수, 각 출력 데이터의 피처 개수
linear = nn.Linear(2,1) # 지금 하는 건 층이 없는 거 

In [59]:
# 학습 
output = linear(data)

print(f'[학습결과]\n{output.shape}\n{output}')

[학습결과]
torch.Size([3, 1])
tensor([[-2.0201],
        [-1.2512],
        [-1.4079]], grad_fn=<AddmmBackward0>)


In [60]:
## 모델 파라미터
linear.weight, linear.weight[0], linear.weight[0][0].item() # 값만 뽑아오고 싶을 때는 .item()

(Parameter containing:
 tensor([[ 0.4016, -0.5240]], requires_grad=True),
 tensor([ 0.4016, -0.5240], grad_fn=<SelectBackward0>),
 0.40155738592147827)

In [61]:
linear.bias

Parameter containing:
tensor([-0.5167], requires_grad=True)

In [62]:
for i, value in enumerate(output.data) :
    print(f'[{i}] {output.data[i].item()}')

[0] -2.0200581550598145
[1] -1.2512279748916626
[2] -1.407936692237854


In [63]:
data

tensor([[8., 9.],
        [6., 6.],
        [3., 4.]])

In [64]:
# 선형식 만들기
w1 = linear.weight[0][0].item() # 가중치 w1
w2 = linear.weight[0][1].item() # 가중치 w2
b = linear.bias[0].item()


y = w1*8. + w2*9. + b # 가중치 1* 8(데이터의 (0,1)) + 가중치 2 * 9 + 편향(b)

print(y)

-2.0200581550598145


#### Linear 결과와 활성화 함수 
- 인공신경망에서 전결합층에 해당하는 Linear 모델에 AF(활성화 함수) 적용

In [65]:
# 활성화 함수 (AF) 적용
# sigmoid 함수 = > 0.0 ~ 1.0 사이의 값으로 변환

af = F.sigmoid(output)
print('학습 결과\n', af)
# 이 부분 빠지면 그냥 선형 회귀가 되는 것.

# 여기서 계산한 결과가 0.5보다 크면 True / 0.5보다 작으면 False

학습 결과
 tensor([[0.1171],
        [0.2225],
        [0.1966]], grad_fn=<SigmoidBackward0>)


- 퍼셉트론 = 가중치 합 + AF 으로 달려 있음..!
- Linear + sigmoid ---> Logistic 회귀

In [67]:
# relu 함수 
# => output 결괏값 >0 : 그대로
# output 결괏값 < = 0 : 0을 반환.
af = F.relu(output)
print(af)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<ReluBackward0>)
