In [57]:
import torch
import torch.nn.functional as F
import torch.optim as optim


In [58]:
# a = torch.IntTensor(10)
# b = torch.Tensor([2.], requires_grad=True)


a = torch.IntTensor(10)
b = torch.tensor(2., requires_grad=True)

In [59]:
print(f'{a.shape}, {a.ndim}, {a.requires_grad}, {a.grad}, {a.is_leaf}, {a.grad_fn}')
print(f'{b.shape}, {b.ndim}, {b.requires_grad}, {b.grad}, {b.is_leaf}, {b.grad_fn}')

torch.Size([10]), 1, False, None, True, None
torch.Size([]), 0, True, None, True, None


In [60]:
c =a.mul(b)

In [61]:
print('c tensor', f'{c.shape}, {c.ndim}, {c.requires_grad}, {c.grad}, {c.is_leaf}, {c.grad_fn}')

c tensor torch.Size([10]), 1, True, None, False, <MulBackward0 object at 0x00000228D3055610>


C:\Users\KDP-48\AppData\Local\Temp\ipykernel_14624\1260115119.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at C:\b\abs_6fueooay2f\croot\pytorch-select_1707342446212\work\build\aten\src\ATen/core/TensorBody.h:494.)
  print('c tensor', f'{c.shape}, {c.ndim}, {c.requires_grad}, {c.grad}, {c.is_leaf}, {c.grad_fn}')


In [62]:
c.backward

<bound method Tensor.backward of tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], grad_fn=<MulBackward0>)>

In [63]:
b.backward

<bound method Tensor.backward of tensor(2., requires_grad=True)>

In [64]:
sgd = optim.SGD

In [65]:
x = torch.ones(5)                           # input tensor
y = torch.zeros(3)                          # expected output
w = torch.randn(5,3, requires_grad=True)
b = torch.randn(3, requires_grad=True)
z = torch.matmul(x, w) + b
#loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)

y2 = torch.zeros(1)                         # expected output
w2 = torch.randn(3, requires_grad=True)
b2 = torch.randn(1, requires_grad=True)
z2 = torch.matmul(z,w2)+b2
#x2 = torch.tensor((5, 5), z)          

#print(z, z.shape, w.shape)

loss = torch.nn.functional.binary_cross_entropy_with_logits(z2, y2)


In [66]:
print('x tensor', f'{x.shape}, {x.ndim}, {x.requires_grad}, {x.grad}, {x.is_leaf}, {x.grad_fn}')
print('y tensor', f'{y.shape}, {y.ndim}, {y.requires_grad}, {y.grad}, {y.is_leaf}, {y.grad_fn}')
print('w tensor', f'{w.shape}, {w.ndim}, {w.requires_grad}, {w.grad}, {w.is_leaf}, {w.grad_fn}')
print('b tensor', f'{b.shape}, {b.ndim}, {b.requires_grad}, {b.grad}, {b.is_leaf}, {b.grad_fn}')
print('z tensor', f'{z.shape}, {z.ndim}, {z.requires_grad}, {z.grad}, {z.is_leaf}, {z.grad_fn}')
print()
#print('x2 tensor', f'{x.shape}, {x.ndim}, {x.requires_grad}, {x.grad}, {x.is_leaf}, {x.grad_fn}')
print('y2 tensor', f'{y2.shape}, {y2.ndim}, {y2.requires_grad}, {y2.grad}, {y2.is_leaf}, {y2.grad_fn}')
print('w2 tensor', f'{w2.shape}, {w2.ndim}, {w2.requires_grad}, {w2.grad}, {w2.is_leaf}, {w2.grad_fn}')
print('b2 tensor', f'{b2.shape}, {b2.ndim}, {b2.requires_grad}, {b2.grad}, {b2.is_leaf}, {b2.grad_fn}')
print('z2 tensor', f'{z2.shape}, {z2.ndim}, {z2.requires_grad}, {z2.grad}, {z2.is_leaf}, {z2.grad_fn}')
print('loss', f'{loss.requires_grad}, {loss.grad}, {loss.is_leaf}, {loss.grad_fn}')


x tensor torch.Size([5]), 1, False, None, True, None
y tensor torch.Size([3]), 1, False, None, True, None
w tensor torch.Size([5, 3]), 2, True, None, True, None
b tensor torch.Size([3]), 1, True, None, True, None
z tensor torch.Size([3]), 1, True, None, False, <AddBackward0 object at 0x00000228D307CB80>

y2 tensor torch.Size([1]), 1, False, None, True, None
w2 tensor torch.Size([3]), 1, True, None, True, None
b2 tensor torch.Size([1]), 1, True, None, True, None
z2 tensor torch.Size([1]), 1, True, None, False, <AddBackward0 object at 0x00000228D307CAF0>
loss True, None, False, <BinaryCrossEntropyWithLogitsBackward0 object at 0x00000228D307CC40>


C:\Users\KDP-48\AppData\Local\Temp\ipykernel_14624\1569453660.py:5: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at C:\b\abs_6fueooay2f\croot\pytorch-select_1707342446212\work\build\aten\src\ATen/core/TensorBody.h:494.)
  print('z tensor', f'{z.shape}, {z.ndim}, {z.requires_grad}, {z.grad}, {z.is_leaf}, {z.grad_fn}')
C:\Users\KDP-48\AppData\Local\Temp\ipykernel_14624\1569453660.py:11: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be popula

In [67]:
w2.grad, b2.grad, w.grad, b.grad

(None, None, None, None)

In [68]:
print(w2, w2.grad)
print(b2, b2.grad)
print(w, w.grad)
print(b, b.grad)

tensor([ 0.5918,  0.0201, -0.1932], requires_grad=True) None
tensor([0.2629], requires_grad=True) None
tensor([[-0.1467,  0.9337,  0.9606],
        [-1.3627,  1.6311,  1.2476],
        [-0.2522, -0.5432, -0.0099],
        [ 1.2500, -1.4319, -0.7281],
        [-0.1357,  0.1278, -0.6782]], requires_grad=True) None
tensor([-1.2911, -0.6386, -0.3170], requires_grad=True) None


In [69]:
loss.backward()

In [70]:
print(w2, w2.grad)
print(b2, b2.grad)
print(w, w.grad)
print(b, b.grad)

tensor([ 0.5918,  0.0201, -0.1932], requires_grad=True) tensor([-0.5312,  0.0216,  0.1302])
tensor([0.2629], requires_grad=True) tensor([0.2740])
tensor([[-0.1467,  0.9337,  0.9606],
        [-1.3627,  1.6311,  1.2476],
        [-0.2522, -0.5432, -0.0099],
        [ 1.2500, -1.4319, -0.7281],
        [-0.1357,  0.1278, -0.6782]], requires_grad=True) tensor([[ 0.1621,  0.0055, -0.0529],
        [ 0.1621,  0.0055, -0.0529],
        [ 0.1621,  0.0055, -0.0529],
        [ 0.1621,  0.0055, -0.0529],
        [ 0.1621,  0.0055, -0.0529]])
tensor([-1.2911, -0.6386, -0.3170], requires_grad=True) tensor([ 0.1621,  0.0055, -0.0529])
