목표 : 5와 5가 아닌 것 분류하는 모델
- 타겟 : y
- 피처 : X

In [2]:
from sklearn.datasets import fetch_openml
mnist = fetch_openml('mnist_784', as_frame=False) # 입력과 타깃 데이터를 담은 (X,y) 튜플로 반환.

c:\ProgramData\anaconda3\envs\EXAM_ML\lib\site-packages\sklearn\datasets\_openml.py:1002: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


In [3]:
X, y = mnist.data, mnist.target

In [4]:
import matplotlib.pyplot as plt

def plot_digit(image) :
    plt.imshow(image, cmap='binary')
    plt.axis('off')

some = X[0]
some_digit = X[0]
some_digit = some_digit.reshape(28,28)
#print(some_digit)
#plot_digit(some_digit)

In [5]:
X_train, X_test, y_train, y_test = X[:60000], X[60000:], y[:60000], y[60000:] # fetch_openml()이 반환한 MNIST 데이터셋은 이미 훈련세트 (앞쪽 6만개), 테스트 세트(뒷쪽1만개)로 나눠져 있음.


### 이진 분류기 훈련<hr>

In [6]:
y_train_5 = (y_train == '5') # 5는 True, 다른 글자는 모두 False
y_test_5 = (y_test == '5')


In [7]:
# 
from sklearn.linear_model import SGDClassifier, LogisticRegression

# 인스턴스 생성
modelS = SGDClassifier(random_state=13)
modelL = LogisticRegression()

# 학습
modelS.fit(X_train, y_train_5)
modelL.fit(X_train, y_train_5)

print(modelS.score(X_test, y_test_5), modelL.score(X_test, y_test_5))

0.9688 0.9779


c:\ProgramData\anaconda3\envs\EXAM_ML\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [8]:
# 이미지 감지
print(modelS.predict([some]), modelL.predict([some]))

[ True] [ True]


In [21]:
from PIL import Image
import numpy as np

path = '2.png' #그림 경로
img = Image.open(path) # 그림 파일 연다
img = img.convert('L') # 그레이스케일로 변경
# img = np.array(img) # narray로 형태 변환
img = np.resize(img,(1,784) )

test_data = 255-img
# img = abs(img.astype('int')-255) 
# img = np.reshape(-1, 3)
# modelS.predict(img) #> 이유는 모르겠지만 안됨., 
modelS.predict(test_data) 
# 5로 쓴 거 말고 다 True 나오는 문제 발생...;;;
# ▶ 내가 쓴 건 다 True로 나옴...현우님이 쓴 건 다 False로 나옴...
# ▶ What's wrong with you.....



array([ True])

In [10]:
from sklearn.model_selection import cross_val_score
cross_val_score(modelS, X_train, y_train_5, cv = 3, scoring='accuracy')

array([0.9515 , 0.95515, 0.9621 ])

In [11]:
from sklearn.dummy import DummyClassifier

dummy = DummyClassifier()
dummy.fit(X_train, y_train_5)
print(any(dummy.predict(X_train)))

False


In [12]:
cross_val_score(dummy, X_train, y_train_5, cv =3, scoring = 'accuracy') 

array([0.90965, 0.90965, 0.90965])